### PR TITLE
Rewrite the bootstrap code

### PR DESCRIPTION
**Pull request by Tyil**
The bootstrap code looked a tad messy and more effort than needed to extend it later on. Besides that, it wasn't POSIX compliant, thus it would be a chore to get it working on some systems that don't come with `bash` by default.

Note that this rewrite is only tested on my machine (funtoo based), not on any of the others that are ment to be supported. I don't have any knowledge on RedHat and their derivatives, so before you merge this, please do some testing on every OS. If anything fails, post the error and I will try to make it work as expected.

### CODE REVIEW

**Comment by melezhik** [comment]
Thanks Patrick.
Looks good for me. 

Hi @Spigell  could you please look at the patch? Especially the arch/fedora parts?

**Comment by melezhik** [comment]
Patrick, as you might have noticed I've modified Travis test to check Sparrowdo bootstrap against the list of "officially" supported OSs, so it's now safe to merge your changes in ...

**Comment by Tyil** [comment]
I read through the commits you made and merged them in (including the `make` part in CentOS specifically), looking at Travis while preparing dinner for possible issues that might appear so I can fix them later today. If it works immediately, it would be ever better ofcourse!

**Comment by melezhik** [comment]
The issue for alpine - https://travis-ci.org/melezhik/sparrowdo/builds/287144061#L3269 is well known, we need to update wget, because default one is too old and doesn't not accept some options, could please add this to your patch?

**Comment by Spigell** [comment]
Greetings. @Tyil , thank you for cleaning this mess with bootstrap section.
On archlinux it doesn't work yet
```
[spigell@hammerhead sparrowdo]$ sparrowdo --bootstrap --verbose --local_mode
sudo bash -c 'export LC_ALL=C ; export GIT_PROTOCOL=https ; export PERL_USE_UNSAFE_INC=1 ; export PATH=/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/local/bin:/usr/sbin/:/sbin/:/bin/:$PATH ; export SPARROW_ROOT=/opt/sparrow ; export SPARROW_CONF_PATH=/opt/sparrow/sparrow-cache/sparrow.yaml ; export OUTTHENTIC_FORMAT=default ; rm -rf /opt/sparrow/sparrowdo-cache && mkdir -m 777 -p /opt/sparrow/sparrowdo-cache'
running sparrow bootstrap for host: 127.0.0.1 ... 
cp /home/spigell/.sparrowdo//opt/sparrow/bootstrap.sh /opt/sparrow/sparrowdo-cache
sudo bash -c 'export LC_ALL=C ; export GIT_PROTOCOL=https ; export PERL_USE_UNSAFE_INC=1 ; export PATH=/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/local/bin:/usr/sbin/:/sbin/:/bin/:$PATH ; export SPARROW_ROOT=/opt/sparrow ; export SPARROW_CONF_PATH=/opt/sparrow/sparrow-cache/sparrow.yaml ; export OUTTHENTIC_FORMAT=default ; bash /opt/sparrow/sparrowdo-cache/bootstrap.sh'
Bootstrap for arch
Your OS (arch) is not supported

```

**Comment by melezhik** [comment]
On alpine issue, upgrading wget, would be:

    apk add wget 

I think we need it before installing cpanm client ...

**Comment by melezhik** [comment]
@Tyil If it possible, can we add an equivalent of Bash "set -e" into bootstrap shell script , so that we die fast at the first error ?

**Comment by Spigell** [comment]
@Tyil , I suggest to you add option --needed for pacman. It will not try to reinstall package if it already exists.

**Comment by Tyil** [comment]
@melezhik I do not know of a POSIX compatible option for this, but I'll ask around if someone knows something for this.

@Spigell Added it to the Archlinux bootstrap section.

The Funtoo image seems to have an empty file at `/etc/os-release`, so I'll have to find something to work around this issue. After that only Alpine seems to be having issues.

**Comment by Spigell** [comment]
@Tyil , why are you install procps-ng to archlinux? in build https://travis-ci.org/melezhik/sparrowdo/builds/287169789 tests succesfull. Myabe need to install for fedora instead?

**Comment by melezhik** [comment]
@Tyil 
> @melezhik I do not know of a POSIX compatible option for this, but I'll ask around if someone knows something for this.

That's not critical.


> The Funtoo image seems to have an empty file at /etc/os-release, so I'll have to find something to work around this issue. After that only Alpine seems to be having issues.

Great!

**Comment by melezhik** [comment]
@Spigell  , on

>@Tyil , why are you install procps-ng to archlinux? in build https://travis-ci.org/melezhik/sparrowdo/builds/287169789 tests for archlinux succesfull. Myabe need to install for fedora instead?

Probably @Tyil is trying to fix that?
https://travis-ci.org/melezhik/sparrowdo/builds/287169789#L3188

`Uptime` is just a example command to run on target host to verify that `sparrowdo --task_run=bash@...` works fine, I will replace it to something more common, for example to `ls -l` ...

**Comment by Tyil** [comment]
@Spigell I was trying to fix what @melezhik just mentioned, I saw an error and tried fixing it. Any command that is defined by POSIX should be fine (there's a list available [in the specification](http://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html)).

**Comment by melezhik** [comment]
@Tyil  thanks for the reference, I've found `ls` in the http://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html , so it will be safe, please merge in this commit - https://github.com/melezhik/sparrowdo/commit/9a1abd5c0719f8631e17544ac6e9d472179d6615 to be in tact

**Comment by Tyil** [comment]
I merged it in locally, and removed the `procps-ng` packages from installation again. I'll wait for Travis to finish up the current test-run before pushing these commits, so I can add some other fixes if needed.

**Comment by melezhik** [comment]
@Tyil  I see errors for funtoo bootstrap, I use pretty old (2 years ago) docker image for funtoo, it might have bad effect, probably we should try this one - https://hub.docker.com/r/ya18/funtoo1/ ( updated 3 years ago )

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=funtoo&starCount=0 - here is the list of funtoo images on DockerHub, not much ...

**Comment by Tyil** [comment]
I was looking at them too. Funtoo recently changed some things around, and uses `ego sync` instead of `emerge --sync`, and uses a different upstream repo to boot. This in turn makes the Funtoo setup fail. All the docker images for Funtoo seem outdated, I was looking into making one myself to publish on Docker Hub to solve the issue.

**Comment by melezhik** [comment]
Ahh, anyway I see that funtoo emerge related errors do not stop Sparrow client from being installed, probably because many packages ( like curl, make so on) are already here, in the image

**Comment by Tyil** [comment]
Most of the tools you need are available by default, but I thought `cpanm` is not.

**Comment by melezhik** [comment]
> All the docker images for Funtoo seem outdated, I was looking into making one myself to publish on Docker Hub to solve the issue.

Good!

**Comment by melezhik** [comment]
> Most of the tools you need are available by default, but I thought cpanm is not.

Yeah, however looking at Travis build log, it is ... :))

**Comment by Tyil** [comment]
I've pushed the merged commits, and split Funtoo and Gentoo. I'm also looking into making travis run parallel builds to test all docker instances. This should speed up testing significantly and make it easier to trace which targets are failing. I might make that into another PR as it is unrelated to the bootstrap script.

**Comment by melezhik** [comment]
Great.

> I might make that into another PR as it is unrelated to the bootstrap script.

If it save time you probably might add paralleling in this PR, but feel free to add this as distinct one.

**Comment by Tyil** [comment]
Some more info on the `set -e` part, I discussed it with some fellow shell hackers, and discovered http://mywiki.wooledge.org/BashFAQ/105. This article ends with

> GreyCat's personal recommendation is simple: don't use set -e. Add your own error checking instead.

And I side with this sentiment after trying to find out exactly what `set -e` does and what I expect of it. It seems to be POSIX, so I can add it if you feel like it would be beneficial.

**Comment by melezhik** [comment]
Well, let's add `set -e` , but bearing in mind its "dubious" implementation we always can remove it if we run into trouble.

**Comment by melezhik** [comment]
Merged, thanks a lot for your work, Patrick

**Comment by melezhik** [comment]
I am going to replace Outthentic OS resolver ( dump_os() ) - https://github.com/melezhik/outthentic/blob/master/lib/Outthentic/Story.pm#L733 by the code you introduce here ( OS resolver part ) .

Sparrow client uses Outthentic::dump_os, Outthentic::_resolve_os  functions to resolve target host's OS.

It might look like duplicated code here ( both Sparrowdo and Sparrow has its own OS resolvers ), however  Sparrow might be run standalone ( not by Sparrowdo ) and needs its own OS resolver.

**Pull request merged**
