### PR TITLE
Make Travis use parallel builds to speed up tests

### PR DESCRIPTION
**Pull request by Tyil**

### CODE REVIEW

**Comment by Tyil** [comment]
The long list of commits should shrink by about 20 entries if #14 gets merged in.

**Comment by Tyil** [comment]
This seems to work. Please merge #14 first, then this PR should merge with no issues afterwards.

**Comment by melezhik** [comment]
Hi @Tyil . Thanks for the improvement, I have never used Travis parallel jobs, looks pretty cool 😄 .
Looks like your PR is not finished yet ?

So far what I can see ( probaly you know ):

- Sparrowdo bootstraps are not triggered 
- sample commmand is uptime, but we choose it ls - l
- You removed core dsl  tests - that's ok, lets skip them for a awhile, I will add them again once this PR is done, I have an idea on *refactoring of ducky.bash tests* and it's seems there is right time for it ...

**Comment by melezhik** [comment]
And another minor thing ( not critical ) - for some reason git shows a descrepancy in bin/sparrowdo inherited from  the previous MR (14), which is strange as it's been already merged.

**Comment by Tyil** [comment]
I had never used Travis parallel jobs either, it was easier than I anticipated.

* This is a bug, that may have been introduced after I made it also run `prove` tests. I'll look into it straight away.
* This was updated after I merged in the latest `master`, it seems the machine I made this PR on wasn't up-to-date.
* Are those the `ducky` tests?

**Comment by melezhik** [comment]
> Are those the ducky tests?

Yes, they are. Let's remove them from Travis for awhile, I'm going to refactor this part. But I am going to do that after merging in your request.

**Comment by Tyil** [comment]
Ah okay, I didn't know what those referred too, and it didn't seem to break anything. My apologies!

**Comment by melezhik** [comment]
@Tyil  I can't see bootstrap test for Centos . You can ignore old way of running centos docker container ( ` -  - docker run --privileged -d --name centos7 --entrypoint  init -v $PWD:/var/ducky -v /sys/fs/cgroup:/sys/fs/cgroup:ro centos `) and just run it as other OSs:

    TEST=bootstrap:centos

**Comment by melezhik** [comment]
> Ah okay, I didn't know what those referred too, and it didn't seem to break anything. My apologies!

No worries :smile:

**Comment by melezhik** [comment]
Thanks for your work, Patrick!  👍

**Pull request merged**
